shellEmulator: true

trustPolicy: no-downgrade

strictPeerDependencies: false

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - mermaid@11.12.1
  - langium@3.3.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - vue-demi

peerDependencyRules:
  allowedVersions:
    citty: 0.2.1
